name: Dependabot Pull Request

on: pull_request

jobs:
  consumer:
    runs-on: macos-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]'}}
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ secrets.GITHUB_TOKEN }}