name: Dependabot PR Consumer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependabot-pr-consumer:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save metadata
        run: |
          echo "UPDATE_TYPE=${{ steps.dependabot-metadata.outputs.update-type }}" > metadata.txt
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> metadata.txt
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> metadata.txt
          echo "SCORE=${{ steps.dependabot-metadata.outputs.compatibility-score }}" >> metadata.txt
      
      - name: List files in workspace
        run: ls -al
      
      - uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: metadata.txt
          
